### ISSUE TITLE
Not Working In The Latest Update

### ISSUE THREAD

**Issue by EMediaArts** [jaysonvelagio/SoftetherAutoInstallMultiPlatform#2]
make: *** No targets specified and no makefile found.  Stop.
mv: cannot stat ‘vpnserver’: No such file or directory
./installer.sh: line 29: cd: /usr/local/vpnserver: No such file or directory
chmod: cannot access ‘vpncmd’: No such file or directory
chmod: cannot access ‘vpnserver’: No such file or directory

./installer.sh: line 40: cd: /usr/local/vpnserver: No such file or directory

**Comment by jaysonvelagio** [comment]
Hi @Driz12 Maybe we should stick on the previous known working release. They have an issue on compilation. i will investigate also for the possible solution thanks.

**Comment by jaysonvelagio** [comment]
@Driz12 the result of my investigation are the following. compilation would not proceed because of the command -no-pie. I will update and fix the latest release so that we can use the latest softether release and can proceed on compilation. I will remove the terms of services too.

**Comment by EMediaArts** [comment]
Great. I will look forward on your update.
